# Generated by Django 5.0.7 on 2024-07-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerminal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangas',
            old_name='Anime',
            new_name='nombre',
        ),
    ]
